# Generated by Django 5.0 on 2024-07-05 06:50

import django.db.models.deletion
import localflavor.generic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('houseno', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(default='Bayern', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('AK', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmallowence', models.CharField(max_length=5)),
                ('dailyallowence', models.CharField(max_length=5)),
                ('fulldayallowence', models.CharField(max_length=5)),
                ('dailycompensation', models.CharField(max_length=5)),
                ('bfreduction', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField(null=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_club', to='expenses.club')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_referee', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_game', to='expenses.game')),
            ],
            options={
                'ordering': ['-startdate'],
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iNOfOneDayTravel', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('iNOfMoreDaysTravel', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('iNOfDaysBetween', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('iNOfNights', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('iNOfTravelDays', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('cComment', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_days', to='expenses.event')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_receipt', to='expenses.event')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('houseno', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, default=' ', max_length=20)),
                ('IBAN', localflavor.generic.models.IBANField(include_countries=('AD', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM', 'VA'), max_length=34, use_nordea_extensions=False)),
                ('BIC', models.CharField(default='BIC', max_length=12)),
                ('nameBank', models.CharField(default='Bankname', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveldate', models.DateTimeField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('startlocation', models.CharField(default=' ', max_length=30)),
                ('endtime', models.TimeField(null=True)),
                ('duration', models.CharField(blank=True, default='00:00 ', max_length=4)),
                ('endlocation', models.CharField(default=' ', max_length=30)),
                ('type', models.CharField(choices=[('KFZ', 'KFZ'), ('Flug', 'Flug'), ('Zug', 'Zug')], default='KFZ', max_length=30)),
                ('km', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_travel', to='expenses.event')),
            ],
            options={
                'ordering': ['traveldate'],
            },
        ),
    ]
