# Generated by Django 4.2.6 on 2023-12-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_referee_houseno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='author',
        ),
    ]
