# Generated by Django 5.0 on 2024-07-19 14:00

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_event_attachment_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=expenses.models.generate_filename),
        ),
    ]
