# Generated by Django 5.0 on 2023-12-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_event_options_remove_event_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytravel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_dailytravels', to='expenses.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_club', to='expenses.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_referee', to='expenses.referee'),
        ),
    ]
