# Generated by Django 5.0 on 2023-12-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_dailytravel_event_alter_event_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytravel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_dailytravel', to='expenses.event'),
        ),
    ]
