# Generated by Django 5.0 on 2023-12-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_event_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_receipt', to='expenses.event'),
        ),
    ]
