# Generated by Django 5.0 on 2023-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_alter_receipt_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
    ]
