# Generated by Django 5.0 on 2023-12-31 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_referee_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='noofbreakfasts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='noofnights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
